### ISSUE TITLE
I have a build for the 32-bit version of Raspbian GNU/Linux 11 (bullseye)

### ISSUE THREAD

**Issue by bassmanitram** [ceinmart/gdrive-linux-aarch64#1]
This is the "file" command output

ELF 32-bit LSB pie executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, BuildID[sha1]=0a2d9e9c77ef306aa90a96644794d109955cc8ff, for GNU/Linux 3.2.0, with debug_info, not stripped

Just tell me where to send it :) (PR?)

**Comment by ceinmart** [comment]
Hi @bassmanitram  , 

I'm not that familiar with GitHub. 
Not sure if you can attach it here in the comments and I put it on my repo.
Or if you can just do a pull request...

**Comment by bassmanitram** [comment]
Well, I was going to fork and PR - but then I I noticed that you repo is called gdrive-linux-*aarch64* - so it doesn't really make sense adding the 32 bit version here.

**Comment by ceinmart** [comment]
no problem... I just renamed it..
